meta_product_name: "Kayapp"
meta_title: "Kayapp - Practice kayak easier not harder!"
meta_description: "An application that merges all the data and gives access to a kayaker community."
meta_image: "canoe.jpg" # should exist in `app/assets/images/...png`
